import React, { useState } from "react"
import "react-data-grid/lib/styles.css"
import "./LoadListComponent.css"

import DataGrid from "react-data-grid"
import DropdownEditor from "../DropDownEditor"

const LoadListComponent = () => {
  const columns = [
    { key: "id", name: "Sr. No.", width: 50 },
    { key: "feederTagNo", name: "FEEDER TAG NO", width: 120 },
    { key: "serviceDescription", name: "SERVICE DESCRIPTION", width: 200 },
    { key: "workingLoadInKW", name: "WORKING LOAD IN KW", width: 150 },
    { key: "standByLoadInKW", name: "STAND-BY LOAD IN KW", width: 150 },
    { key: "kva", name: "KVA", width: 80 },
    { key: "starterType", name: "STARTER TYPE", width: 120, editable: true},
    { key: "supplyVoltage", name: "SUPPLY VOLTAGE", width: 130 },
    { key: "phase", name: "PHASE", width: 100 },
    { key: "startingTime", name: "STARTING TIME", width: 120 },
    { key: "eocrApplicable", name: "EOCR APPLICABLE", width: 140 },
    { key: "lpbsType", name: "LPBS TYPE", width: 100 },
    { key: "controlScheme", name: "CONTROL SCHEME", width: 140 },
    { key: "panel", name: "PANEL", width: 100 },
    { key: "busSegregation", name: "BUS SEGREGATION", width: 140 },
    { key: "motorRpm", name: "MOTOR RPM", width: 100 },
    { key: "typeOfMotorMounting", name: "TYPE OF MOTOR MOUNTING", width: 180 },
    { key: "motorFrameSize", name: "MOTOR FRAME SIZE", width: 140 },
    { key: "motorGd2", name: "MOTOR GD 2", width: 100 },
    { key: "equipmentGd2", name: "EQUIPMENT GD2", width: 130 },
    { key: "bkw", name: "BKW", width: 80 },
    { key: "typeOfCoupling", name: "TYPE OF COUPLING", width: 140 },
    { key: "package", name: "PACKAGE", width: 100 },
    { key: "area", name: "AREA", width: 80 },
    { key: "standard", name: "STANDARD", width: 100 },
    { key: "zone", name: "ZONE", width: 80 },
    { key: "gasGroup", name: "GAS GROUP", width: 100 },
    { key: "temperatureClass", name: "TEMPERATURE CLASS", width: 150 },
    { key: "remark", name: "REMARK", width: 100 },
    { key: "rev", name: "REV.", width: 70 },
    { key: "spaceHeater", name: "SPACE HEATER", width: 120 },
    { key: "bearingRtd", name: "BEARING RTD", width: 120 },
    { key: "windingRtd", name: "WINDING RTD", width: 120 },
    { key: "thermistor", name: "THERMISTOR", width: 100 },
    { key: "typeOfBearing", name: "TYPE OF BEARING", width: 140 },
    { key: "powerFactor", name: "POWER FACTOR", width: 120 },
    { key: "motorEfficiency", name: "MOTOR EFFICIENCY", width: 140 },
    { key: "localIsolator", name: "LOCAL ISOLATOR", width: 130 },
    { key: "panelAmmeter", name: "PANEL AMMETER", width: 130 },
    { key: "motorMake", name: "MOTOR MAKE", width: 110 },
    { key: "motorScope", name: "MOTOR SCOPE", width: 120 },
    { key: "motorLocation", name: "MOTOR LOCATION", width: 130 },
  ]
  const rows = [
    {
      id: 1,
      feederTagNo: "FT-001",
      serviceDescription: "Pump Motor 1",
      workingLoadInKW: 75,
      standByLoadInKW: 0,
      kva: 90,
      starterType: "VFD",
      supplyVoltage: "415 VAC",
      phase: "3 Phase",
      startingTime: "10 sec",
      eocrApplicable: "Yes",
      lpbsType: "Type-1",
      controlScheme: "Scheme-5",
      panel: "MCC-1",
      busSegregation: "A",
      motorRpm: 1000,
      typeOfMotorMounting: "Foot Mounted (B3)",
      motorFrameSize: "315S",
      motorGd2: 0.5,
      equipmentGd2: 0.8,
      bkw: 70,
      typeOfCoupling: "Flexible",
      package: "NA",
      area: "Safe",
      standard: "IEC",
      zone: "NA",
      gasGroup: "NA",
      temperatureClass: "NA",
      remark: "",
      rev: "R0",
      spaceHeater: "Yes",
      bearingRtd: "Yes",
      windingRtd: "Yes",
      thermistor: "Yes",
      typeOfBearing: "Ball",
      powerFactor: 0.8,
      motorEfficiency: "IE-2",
      localIsolator: "Yes",
      panelAmmeter: "Y-Phase With CT",
      motorMake: "TL Std",
      motorScope: "THERMAX",
      motorLocation: "INDOOR",
    },
    {
      id: 2,
      feederTagNo: "FT-002",
      serviceDescription: "Compressor Motor 1",
      workingLoadInKW: 110,
      standByLoadInKW: 0,
      kva: 132,
      starterType: "DOL",
      supplyVoltage: "415 VAC",
      phase: "3 Phase",
      startingTime: "5 sec",
      eocrApplicable: "No",
      lpbsType: "Type-2",
      controlScheme: "Scheme-3",
      panel: "MCC-2",
      busSegregation: "B",
      motorRpm: 1500,
      typeOfMotorMounting: "Flange Mounted (B5)",
      motorFrameSize: "280M",
      motorGd2: 0.6,
      equipmentGd2: 1.0,
      bkw: 100,
      typeOfCoupling: "Direct",
      package: "NA",
      area: "Hazardous",
      standard: "ATEX",
      zone: "Zone 2",
      gasGroup: "IIA",
      temperatureClass: "T3",
      remark: "Ex-proof",
      rev: "R1",
      spaceHeater: "No",
      bearingRtd: "No",
      windingRtd: "Yes",
      thermistor: "Yes",
      typeOfBearing: "Roller",
      powerFactor: 0.85,
      motorEfficiency: "IE-3",
      localIsolator: "No",
      panelAmmeter: "Digital",
      motorMake: "ABB",
      motorScope: "VENDOR",
      motorLocation: "OUTDOOR",
    },
    // Add more rows with similar structure but different values
    // ...
  ]

  console.log(rows)

  return <DataGrid columns={columns} rows={rows} className="my-custom-grid" />
}

export default LoadListComponent
