export const feederConfigItems2 = [
  {
    id: 1,
    name: "DOL Starter",
    inputType: "dropdown",
    note: "KW Including and below",
    group: "group_1",
    options: [],
    placeholder: "Select",
    value: "",
    checked: false,
    identity: "dol",
  },
  {
    id: 2,
    name: "Star Delta Starter",
    inputType: "dropdown",
    note: "KW Including and above",
    group: "group_1",
    options: [],
    placeholder: "Select",
    value: "",
    checked: false,
    identity: "starDelta",
  },
  {
    id: 284,
    name: "Ammeter",
    inputType: "dropdown",
    note: "KW Including and above",
    group: "group_1",
    options: [],
    placeholder: "Select",
    value: "",
    checked: false,
    identity: "starDeltakW",
  },
  {
    id: 3,
    name: "Ammeter Configuration",
    inputType: "dropdown",
    note: "",
    group: "group_1",
    options: [],
    placeholder: "Select",
    value: "",
    checked: false,
    identity: "starDeltaCt",
  },
  {
    id: 4,
    name: "MCC Switchgear type",
    inputType: "dropdown",
    note: "",
    group: "group_1",
    options: [],
    placeholder: "Select",
    value: "Type II coordination-Fuseless",
    checked: false,
    identity: "mccSwitchGearType",
  },
  {
    id: 5,
    name: "Switchgear Combination",
    inputType: "dropdown",
    note: "",
    group: "group_1",
    options: ["With MCB", "Without MCB"],
    placeholder: "Select",
    value: "Without MCB", // Default value
    checked: false,
    identity: "mccSwitchGearComb",
  },
  // New element with two dropdowns
  {
    id: 6,
    name: "Combined Dropdowns Example", // Name for the combined dropdowns
    inputType: "combined", // New input type to indicate it contains multiple dropdowns
    note: "Select values for both dropdowns",
    group: "group_1",
    properties: [
      {
        name: "First Dropdown",
        options: ["Option A", "Option B", "Option C"],
        placeholder: "Select First Option",
        value: "",
        checked: false,
        identity: "firstDropdown",
      },
      {
        name: "Second Dropdown",
        options: ["Option D", "Option E", "Option F"],
        placeholder: "Select Second Option",
        value: "",
        checked: false,
        identity: "secondDropdown",
      },
    ],
    extra: "",
    inputName: "",
  },
]
