export const HOME_PAGE = "/"
export const PROJECT_LIST_PAGE = "/project_list"
export const PACKAGE_PAGE = "/package-management"
export const COMPLETE_PROJECT_PAGE = "/complete_project"
export const USER_MANAGEMENT_PAGE = "/user-management"
