name: Deploy to GitHub Container Registry

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23
          cache: yarn

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      # Step 4: Build the Next.js application
      - name: Build Next.js App
        run: yarn build

      # Step 5: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Step 6: Build the Docker image with secrets
      - name: Build Docker Image
        run: |
          docker build \
            --build-arg FRAPPE_ADMIN_AUTH_SECRET=${{ secrets.FRAPPE_ADMIN_AUTH_SECRET }} \
            --build-arg AWS_S3_BUCKET_BASE_FOLDER=${{ secrets.AWS_S3_BUCKET_BASE_FOLDER }} \
            --build-arg AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }} \
            --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --build-arg AWS_S3_REGION=${{ secrets.AWS_S3_REGION }} \
            --build-arg NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }} \
            --build-arg FRAPPE_BASE_URL=${{ secrets.FRAPPE_BASE_URL }} \
            --build-arg NEXT_PUBLIC_FRAPPE_DOMAIN_NAME=${{ secrets.NEXT_PUBLIC_FRAPPE_DOMAIN_NAME }} \
            --build-arg NODE_ENV=${{ secrets.NODE_ENV }} \
            --build-arg AUTH_SECRET=${{ secrets.AUTH_SECRET }} \
            --build-arg FRAPPE_ADMIN_AUTH_KEY=${{ secrets.FRAPPE_ADMIN_AUTH_KEY }} \
            -t ghcr.io/inventive-business-solutions/thermax-frontend:latest .

      # Step 7: Push the Docker image to GitHub Container Registry
      - name: Push Docker Image
        run: docker push ghcr.io/inventive-business-solutions/thermax-frontend:latest
